#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Lugares que estaban en la lista "NY 2026" de Google Maps (compartida por Thais, 139 lugares)
y NO estaban en el catálogo. Leídos del Chrome de Juan el 25/8/2026.

Interés por defecto 1/1 ("quizás") a propósito: vienen de la lista, no de una decisión —
así no distorsionan la hoja de Costos, que suma solo los marcados 2. Subilos en la app.

Las coordenadas se resuelven por geocodificación (Nominatim) sobre el MISMO string que usa
el botón de Google Maps, así el pin del mapa y el link apuntan al mismo lugar.
"""

# (id, nombre, cat, barrio, boro, subte, dirección, costo, horas, por qué, mainstream, subcategoría)
G = [
 # ── COMIDA ───────────────────────────────────────────────────────────────────
 ("bleeckerpizza", "Bleecker Street Pizza", "comida", "West Village", "Manhattan",
  "Christopher St-Sheridan Sq (1)", "69 7th Ave S", 8, 0.4,
  "Slice de barrio con fila constante: la Nonna Maria (vodka sauce) es la que la puso en el mapa.", False, "Pizzería"),
 ("adelshalal", "Adel's Famous Halal Food", "comida", "Astoria", "Queens",
  "Broadway (N,W)", "", 12, 0.5,
  "Carrito halal de culto: arroz amarillo, pollo y la salsa blanca, a precio de carrito.", False, "Comida al paso"),
 ("greydog", "The Grey Dog - Union Square", "comida", "Union Square", "Manhattan",
  "14 St-Union Sq (4,5,6,L,N,Q,R,W)", "90 University Pl", 25, 0.75,
  "Café-restaurante de barrio, desayuno todo el día, el antídoto al brunch de cola.", False, "Café y brunch"),
 ("popsbagels", "Pop's Bagels Nolita", "comida", "Nolita", "Manhattan",
  "Spring St (6)", "", 10, 0.4,
  "La camada nueva del bagel neoyorquino: masa más chica y densa, hecha por tandas.", False, "Panadería y bagels"),
 ("manhatta", "Manhatta", "comida", "Financial District", "Manhattan",
  "Wall St (2,3)", "28 Liberty St, piso 60", 90, 1.75,
  "El restaurante de Danny Meyer en el piso 60: la vista de un observatorio pago, sentado y con vino.", True, "Restaurante con vista"),
 ("huehouse", "Hue House", "comida", "Manhattan", "Manhattan",
  "", "", 45, 1.25,
  "Taiwanés moderno, cocina de isla sin concesiones al paladar turístico.", False, "Restaurante étnico"),
 ("doublechicken", "Double Chicken Please", "comida", "Lower East Side", "Manhattan",
  "Delancey St-Essex St (F,J,M,Z)", "115 Allen St", 40, 1.5,
  "Entra en las listas de mejores bares del mundo: cócteles que replican platos (el 'Cold Pizza' es real).", True, "Coctelería"),
 ("goldendiner", "Golden Diner", "comida", "Two Bridges", "Manhattan",
  "East Broadway (F)", "123 Madison St", 25, 0.75,
  "Diner americano cruzado con cocina asiática, debajo del puente de Manhattan. Sin pose.", False, "Diner clásico"),
 ("sakagura", "Sakagura", "comida", "Midtown East", "Manhattan",
  "Grand Central-42 St (4,5,6,7,S)", "211 E 43rd St (sótano)", 60, 1.5,
  "Izakaya escondido en el SÓTANO de un edificio de oficinas: se entra por el lobby y se baja. 200 sakes.", False, "Restaurante étnico"),
 ("barkbbq", "Bark Barbecue", "comida", "Queens", "Queens",
  "", "", 25, 1.0,
  "Barbacoa texana con acento mexicano, de las mejor rankeadas de la ciudad.", False, "Comida al paso"),
 ("deluxegreenbo", "Deluxe Green Bo", "comida", "Chinatown", "Manhattan",
  "Canal St (6,N,Q,R,W,J,Z)", "66 Bayard St", 20, 1.0,
  "Shanghainés viejo de Chinatown: los soup dumplings y el pork chop rice cake.", False, "Restaurante étnico"),
 ("beastbutterflies", "Beast & Butterflies Times Square", "comida", "Times Square", "Manhattan",
  "42 St-Port Authority (A,C,E)", "", 35, 1.25,
  "Comedor del M Social: una alternativa sentada y tranquila en pleno Times Square.", False, "Restaurante americano"),
 ("johnspizzeria", "John's of Times Square", "comida", "Theater District", "Manhattan",
  "42 St-Port Authority (A,C,E)", "260 W 44th St", 25, 1.0,
  "Pizzería de horno a leña DENTRO de una iglesia reconvertida, con los vitrales intactos. Sin porciones: pizza entera.", True, "Pizzería"),
 ("sarges", "Sarge's Delicatessen & Diner", "comida", "Murray Hill", "Manhattan",
  "33 St (6)", "548 3rd Ave", 30, 1.0,
  "Deli judío de 1964 abierto 24 horas: el pastrami sin la cola de Katz's.", False, "Deli y pastrami"),
 ("ticktock", "Tick Tock Diner NY", "comida", "Midtown West", "Manhattan",
  "34 St-Penn Station (1,2,3,A,C,E)", "481 8th Ave", 25, 0.75,
  "Diner art déco cromado frente a Penn Station. Útil de verdad los días de tren.", False, "Diner clásico"),
 ("boathouse", "Central Park Boathouse", "comida", "Central Park", "Manhattan",
  "72 St (B,C)", "E 72nd St & Park Dr N", 45, 1.25,
  "Almuerzo sobre el lago, con los botes de remo pasando. Es LA postal del parque, y se come bien.", True, "Restaurante con vista"),
 ("starbucksroastery", "Starbucks Reserve Roastery", "comida", "Chelsea", "Manhattan",
  "14 St (A,C,E)", "61 9th Ave", 15, 0.75,
  "La tostadora gigante a la vista: más fábrica-espectáculo que café. Entrar es gratis.", True, "Café y brunch"),
 ("bluestonelane", "Bluestone Lane UWS Café", "comida", "Upper West Side", "Manhattan",
  "79 St (1)", "", 18, 0.6,
  "Café australiano: flat white decente y avocado toast, a tres cuadras de The Beacon.", False, "Café y brunch"),
 ("shakeshack", "Shake Shack (Columbus Circle / Theater District)", "comida", "Midtown", "Manhattan",
  "59 St-Columbus Circle (1,A,B,C,D)", "", 15, 0.5,
  "El burger de Madison Square Park convertido en cadena. En la lista estaban tres sucursales: esta es la más cómoda.", True, "Hamburguesería"),
 ("sarabeths", "Sarabeth's Central Park South", "comida", "Midtown", "Manhattan",
  "59 St-Columbus Circle (1,A,B,C,D)", "40 Central Park S", 35, 1.0,
  "El brunch clásico del Upper East/Central Park South. Mermeladas propias, cola los domingos.", True, "Café y brunch"),
 ("arabica", "% Arabica", "comida", "Manhattan", "Manhattan",
  "", "", 10, 0.4,
  "Café japonés-kuwaití minimalista, buen espresso para llevar caminando.", False, "Café y brunch"),
 ("eataly", "Eataly Flatiron", "comida", "Flatiron", "Manhattan",
  "23 St (R,W,F,M)", "200 5th Ave", 30, 1.25,
  "Mercado italiano gigante: pasta fresca, mostradores de quesos y varias barras para comer parado.", True, "Mercado y food hall"),
 ("jackswifefreda", "Jack's Wife Freda", "comida", "SoHo", "Manhattan",
  "Spring St (6)", "224 Lafayette St", 30, 1.0,
  "Brunch sudafricano-israelí, chico y siempre lleno. A dos cuadras del JGStay.", True, "Café y brunch"),
 ("juniors", "Junior's Restaurant and Bakery", "comida", "Theater District", "Manhattan",
  "49 St (N,R,W)", "1626 Broadway", 30, 1.0,
  "El cheesecake de Brooklyn, en su sucursal de Times Square. Porciones absurdas.", True, "Diner clásico"),
 ("carmines", "Carmine's 44th Street", "comida", "Theater District", "Manhattan",
  "42 St-Times Sq", "200 W 44th St", 45, 1.5,
  "Italiano familiar de platos para compartir, pensado para antes del teatro. Reservar.", True, "Restaurante étnico"),
 ("cultureespresso", "Culture Espresso", "comida", "Midtown", "Manhattan",
  "34 St-Herald Sq (B,D,F,M,N,Q,R,W)", "72 W 38th St", 8, 0.4,
  "Café pequeño famoso por su cookie de chocolate, que compite en serio con Levain.", False, "Café y brunch"),
 ("lacabra", "La Cabra Bakery", "comida", "East Village", "Manhattan",
  "Astor Pl (6)", "152 2nd Ave", 12, 0.5,
  "Panadería danesa: el cardamom bun y el laminado son de otro nivel.", False, "Panadería y bagels"),
 ("dominiqueansel", "Dominique Ansel Bakery", "comida", "SoHo", "Manhattan",
  "Spring St (C,E)", "189 Spring St", 15, 0.5,
  "El obrador donde se inventó el cronut. Ir temprano o se agota lo bueno.", True, "Panadería y bagels"),
 ("piesnthighs", "Pies 'n' Thighs", "comida", "Williamsburg", "Brooklyn",
  "Marcy Av (J,M,Z)", "166 S 4th St", 25, 1.0,
  "Pollo frito sureño y pies, al pie del puente de Williamsburg. Cerca de Peter Luger.", False, "Restaurante étnico"),
 ("amorino", "Amorino", "comida", "Manhattan", "Manhattan",
  "", "", 10, 0.3,
  "Gelato servido en forma de flor. Más foto que helado, pero el helado es bueno.", True, "Heladería y dulces"),
 ("zabars", "Zabar's", "comida", "Upper West Side", "Manhattan",
  "79 St (1)", "2245 Broadway", 15, 0.75,
  "La institución del Upper West Side desde 1934: quesos, ahumados y un café arriba. A pasos de The Beacon.", False, "Mercado y food hall"),
 ("dough", "Dough Doughnuts", "comida", "Midtown", "Manhattan",
  "47-50 Sts-Rockefeller Ctr (B,D,F,M)", "", 8, 0.3,
  "Donas grandes y glaseadas (hibisco, dulce de leche). Buen desvío de cinco minutos.", False, "Heladería y dulces"),
 ("krispykreme", "Krispy Kreme Times Square", "comida", "Times Square", "Manhattan",
  "42 St-Times Sq", "1601 Broadway", 8, 0.4,
  "El flagship con la línea de glaseado a la vista y el cartel gigante. Espectáculo, no gastronomía.", True, "Heladería y dulces"),
 ("russcafe", "Russ & Daughters Cafe", "comida", "Lower East Side", "Manhattan",
  "Delancey St-Essex St (F,J,M,Z)", "127 Orchard St", 40, 1.25,
  "La versión SENTADA del appetizing de 1914: mismo salmón, con mesa y platos. Distinto del local de Houston.", True, "Deli y pastrami"),
 ("bibliotheque", "Bibliothèque", "comida", "Manhattan", "Manhattan",
  "", "", 25, 1.0,
  "Café-librería para sentarse un rato largo sin que te apuren.", False, "Café y brunch"),
 ("morningsidemarket", "Morningside Park Farmers Market", "comida", "Morningside Heights", "Manhattan",
  "116 St-Columbia University (1)", "", 0, 0.5,
  "Feria de productores del barrio de Columbia. Solo algunos días: verificar antes de ir.", False, "Mercado y food hall"),

 # ── BARES Y MÚSICA ───────────────────────────────────────────────────────────
 ("rudysbar", "Rudy's Bar & Grill", "musica", "Hell's Kitchen", "Manhattan",
  "50 St (C,E)", "627 9th Ave", 10, 1.0,
  "Dive bar de 1933 con el cerdo gigante en la puerta: cerveza barata y HOT DOGS GRATIS con la consumición.", False, "Bar con música"),

 # ── ARQUITECTURA, IGLESIAS Y CALLES ──────────────────────────────────────────
 ("oldstpats", "Basilica of St. Patrick's Old Cathedral", "arq", "Nolita", "Manhattan",
  "Spring St (6)", "263 Mulberry St", 0, 0.5,
  "La catedral ORIGINAL de San Patricio (1815), no la de la Quinta: cementerio amurallado y catacumbas visitables. A tres cuadras del JGStay.", False, "Templo"),
 ("trinitychurch", "Trinity Church", "arq", "Financial District", "Manhattan",
  "Wall St (4,5)", "89 Broadway", 0, 0.5,
  "Neogótica de 1846, la torre más alta de NY durante medio siglo. En su cementerio está Alexander Hamilton.", False, "Templo"),
 ("federalhall", "Federal Hall National Memorial", "museo", "Financial District", "Manhattan",
  "Wall St (4,5)", "26 Wall St", 0, 0.75,
  "Donde Washington juró como primer presidente. GRATIS, y casi siempre vacío pese a estar frente a la Bolsa.", False, "Museo de historia"),
 ("earthroom", "The New York Earth Room", "museo", "SoHo", "Manhattan",
  "Prince St (N,R,W)", "141 Wooster St, 2º piso", 0, 0.4,
  "127 metros cúbicos de tierra ocupando un loft del SoHo desde 1977. Gratis, absurdo y silencioso: de lo más no-turístico que hay.", False, "Museo de arte"),
 ("wildtable", "Wild Table of Love", "arq", "Manhattan", "Manhattan",
  "", "", 0, 0.25,
  "Instalación escultórica al aire libre. Parada de foto de cinco minutos.", False, "Parque de esculturas"),
 ("frauncestavern", "Fraunces Tavern", "arq", "Financial District", "Manhattan",
  "Broad St (J,Z)", "54 Pearl St", 20, 1.0,
  "La taberna de 1762 donde Washington se despidió de sus oficiales. Museo arriba, bar funcionando abajo.", False, "Casa y calle histórica"),
 ("bigelow", "C.O. Bigelow Chemists", "arq", "West Village", "Manhattan",
  "Christopher St-Sheridan Sq (1)", "414 6th Ave", 0, 0.3,
  "La farmacia más antigua de Estados Unidos (1838), con el mobiliario original. Entrar es gratis.", False, "Tienda con historia"),
 ("housingworks", "Housing Works Bookstore", "arq", "SoHo", "Manhattan",
  "Spring St (6)", "126 Crosby St", 0, 0.6,
  "Librería de dos pisos con café: todo lo donado y toda la ganancia va a personas con VIH sin hogar.", False, "Tienda con historia"),
 ("bhphoto", "B&H Photo Video", "arq", "Midtown West", "Manhattan",
  "34 St-Penn Station (1,2,3,A,C,E)", "420 9th Ave", 0, 1.0,
  "La tienda de fotografía mítica: cintas transportadoras cruzando el techo y vendedores jasídicos que saben todo. CIERRA sábados.", False, "Tienda con historia"),
 ("louisvuitton", "Louis Vuitton", "arq", "Midtown", "Manhattan",
  "5 Av/53 St (E,M)", "1 E 57th St", 0, 0.5,
  "Flagship de la Quinta. En la lista de Google, presumiblemente para compras.", True, "Tienda con historia"),
 ("mmsworld", "M&M'S World New York", "arq", "Times Square", "Manhattan",
  "42 St-Times Sq", "1600 Broadway", 0, 0.5,
  "Tres pisos de merchandising en Times Square. Es lo que promete, ni más ni menos.", True, "Tienda con historia"),
 ("artistsfleas", "Artists & Fleas Williamsburg", "arq", "Williamsburg", "Brooklyn",
  "Bedford Av (L)", "70 N 7th St", 0, 0.75,
  "Mercado de diseñadores y vintage, fines de semana. Está en el camino del sábado de Brooklyn.", False, "Tienda con historia"),
 ("rockefeller", "Rockefeller Center", "arq", "Midtown", "Manhattan",
  "47-50 Sts-Rockefeller Ctr (B,D,F,M)", "45 Rockefeller Plaza", 0, 0.75,
  "El conjunto art déco a nivel de calle: la plaza hundida, el Atlas y el mural de Prometeo. Gratis; el Top of the Rock es aparte.", True, "Arquitectura moderna"),
 ("hudsonyards", "Hudson Yards", "arq", "Hudson Yards", "Manhattan",
  "34 St-Hudson Yards (7)", "20 Hudson Yards", 0, 0.75,
  "El complejo entero: el Vessel, The Shed y el mall. Es el arranque natural del High Line.", True, "Arquitectura moderna"),
 ("brooklynbridge", "Puente de Brooklyn", "arq", "Civic Center", "Manhattan",
  "Brooklyn Bridge-City Hall (4,5,6)", "", 0, 1.0,
  "Cruzarlo a pie es el clásico que sí lo vale. Entrada peatonal frente a City Hall; después de las 16 se llena.", True, "Puente"),
 ("cannonswalk", "Cannon's Walk", "arq", "South Street Seaport", "Manhattan",
  "Fulton St (2,3,4,5,A,C,J,Z)", "", 0, 0.3,
  "Callejón adoquinado del Seaport entre edificios del siglo XIX. Atajo con encanto.", False, "Casa y calle histórica"),
 ("stonest", "Stone St", "arq", "Financial District", "Manhattan",
  "Broad St (J,Z)", "", 0, 0.5,
  "Calle adoquinada peatonal, con las mesas de los bares afuera. De 5 a 8 PM es el after office más lindo de FiDi.", False, "Casa y calle histórica"),
 ("wallst", "Wall St", "arq", "Financial District", "Manhattan",
  "Wall St (4,5)", "", 0, 0.4,
  "El cañón de piedra: la Bolsa, Federal Hall y Trinity al fondo. Se ve en veinte minutos.", True, "Casa y calle histórica"),
 ("doyers", "Doyers St", "arq", "Chinatown", "Manhattan",
  "Canal St (6,N,Q,R,W,J,Z)", "", 0, 0.25,
  "La curva imposible del 'Bloody Angle', con el mural. Media cuadra que resume Chinatown.", False, "Casa y calle histórica"),
 ("princest", "Prince St", "arq", "SoHo", "Manhattan",
  "Prince St (N,R,W)", "", 0, 0.5,
  "El eje comercial del SoHo, entre fachadas de hierro fundido y puestos de arte en la vereda.", True, "Casa y calle histórica"),
 ("washingtonst", "Washington St (la foto de DUMBO)", "arq", "DUMBO", "Brooklyn",
  "High St (A,C), York St (F)", "Washington St & Water St", 0, 0.25,
  "El encuadre exacto del puente de Manhattan entre los edificios. Llegar temprano o hay cola para la foto.", True, "Casa y calle histórica"),
 ("smallpox", "Smallpox Memorial Hospital", "arq", "Roosevelt Island", "Manhattan",
  "Teleférico o F a Roosevelt Island", "", 0, 0.3,
  "La única ruina oficialmente protegida de NY: hospital gótico de 1856, iluminado de noche. Se pasa camino al FDR Park.", False, "Casa y calle histórica"),
 ("rilighthouse", "Roosevelt Island Lighthouse", "arq", "Roosevelt Island", "Manhattan",
  "Teleférico o F a Roosevelt Island", "", 0, 0.4,
  "Faro de 1872 en la punta NORTE de la isla (el FDR Park está en la sur): 20 minutos de caminata y casi nadie.", False, "Casa y calle histórica"),
 ("belvedere", "Castillo Belvedere", "mirador", "Central Park", "Manhattan",
  "81 St-Museum of Natural History (B,C)", "", 0, 0.5,
  "Castillo victoriano en el punto más alto del parque, con la terraza sobre el Turtle Pond. Gratis.", True, "Mirador gratis"),

 # ── PARQUES Y AGUA ───────────────────────────────────────────────────────────
 ("pier57", "Pier 57", "mirador", "Chelsea", "Manhattan",
  "14 St (A,C,E)", "25 11th Ave", 0, 0.75,
  "Parque en la AZOTEA de un muelle, gratis, con el Hudson de frente y un food hall abajo. Al lado del Little Island.", False, "Mirador gratis"),
 ("pier35", "Pier 35", "mirador", "Lower East Side", "Manhattan",
  "East Broadway (F)", "", 0, 0.4,
  "Eco-park con hamacas frente al puente de Manhattan. Vacío y bien orientado al atardecer.", False, "Mirador gratis"),
 ("batterypark", "Battery Park", "parque", "Financial District", "Manhattan",
  "Bowling Green (4,5), South Ferry (1)", "", 0, 0.75,
  "La punta sur de la isla: la bahía, la Estatua a lo lejos y el embarcadero del ferry. Gratis.", True, "Parque urbano"),
 ("prospectpark", "Prospect Park", "parque", "Park Slope", "Brooklyn",
  "Grand Army Plaza (2,3)", "", 0, 1.5,
  "El parque que Olmsted y Vaux consideraban SU obra maestra, mejor que Central Park: más bosque y menos turistas.", False, "Parque urbano"),

 # ── MUSEOS Y EXPERIENCIAS ────────────────────────────────────────────────────
 ("balloonmuseum", "Balloon Museum NYC - DAYDREAM", "museo", "Manhattan", "Manhattan",
  "", "", 40, 1.25,
  "Arte inflable inmersivo, muy fotografiable. Exposición itinerante: verificar que siga en cartel.", True, "Museo temático"),
 ("paintnpour", "Paint 'N Pour", "evento", "Manhattan", "Manhattan",
  "", "", 45, 2.0,
  "Taller de pintura con copa de vino. Se reserva por sesión.", False, "Taller y experiencia"),
 ("timetopaint", "Time To Paint - Painting Studio", "evento", "Manhattan", "Manhattan",
  "", "", 45, 2.0,
  "Estudio para pintar por sesión, mismo formato que Paint 'N Pour.", False, "Taller y experiencia"),

 # ── BARRIOS ──────────────────────────────────────────────────────────────────
 ("soho", "SoHo", "barrio", "SoHo", "Manhattan",
  "Prince St (N,R,W), Spring St (6)", "", 0, 1.5,
  "El mayor conjunto de arquitectura de hierro fundido del mundo, hoy con las marcas abajo y los lofts arriba. Es el barrio del JGStay.", True, "Barrio histórico"),
 ("eastvillage", "East Village", "barrio", "East Village", "Manhattan",
  "Astor Pl (6), 1 Av (L)", "", 0, 1.5,
  "Lo que queda del downtown punk y ucraniano: bares de tugurio, St. Marks y jardines comunitarios.", False, "Barrio histórico"),

 # ── TRANSPORTE ───────────────────────────────────────────────────────────────
 ("nycferry", "NYC Ferry DUMBO → Wall St", "transporte", "East River", "Manhattan",
  "Pier 1 DUMBO / Pier 11 Wall St", "", 4, 0.5,
  "$4,50 y cruza el East River con el puente de Brooklyn de frente: la vista del crucero turístico por precio de subte.", False, "Ferry y teleférico"),
]
